### ISSUE TITLE
Repl_slave_priv does not work as suggested in init.pp

### ISSUE THREAD

**Issue by LarsFronius** [arioch/puppet-percona#21]
There is a use case to set Repl_slave_priv in init.pp of puppet-percona, which unfortunately does not work.
I have written

```
percona::rights {'Set rights for replication':
        user     => 'repl',
        password => 'repl',
        database => ['%'],
        priv     => 'Repl_slave_priv',
        host     => '192.168.50.6',
}
```

in my site.pp

If I run puppet with --debug --verbose I see

```
Error: The privilege 'repl_slave_priv' is not valid.
Error: /Stage[main]//Node[default]/Percona::Rights[Set rights for replication]/Mysql_grant[repl@192.168.50.6/%]/privileges: change from  to repl_slave_priv failed: The privilege 'repl_slave_priv' is not valid.
```

Seems like a validation issue in modules/percona/lib/puppet/provider/mysql_grant/mysql.rb ?!

**Comment by erik-smit** [comment]
Good to see I'm not the only one breaking his head over this issue.

**Comment by erik-smit** [comment]
Bingo!

```
mysql> describe user "Repl_slave_priv";
+-----------------+---------------+------+-----+---------+-------+
| Field           | Type          | Null | Key | Default | Extra |
+-----------------+---------------+------+-----+---------+-------+
| Repl_slave_priv | enum('N','Y') | NO   |     | N       |       |
+-----------------+---------------+------+-----+---------+-------+
1 row in set (0.00 sec)

mysql> describe db "Repl_slave_priv";
Empty set (0.00 sec)
```

repl_slave_priv is a privilege defined in the 'user' table. 
So it can only be granted to a user. 
But the example resource defines a database, so mysql_grant tries to grant it as a database-level privilege.

So it's not as obscure as I thought, but it _is_ a good timewaster. :)
I've pullrequested a fix https://github.com/arioch/puppet-percona/pull/30.
