### ISSUE TITLE
repository is not added to sources.list

### ISSUE THREAD

**Issue by runa** [arioch/puppet-percona#29]
Dear Arioch:

I'm using your module as:

```
class { 'apt': }
class { 'percona':
  server => true,
  percona_version => '5.6',

}
include percona

Class['apt'] -> Class['percona']
```

but when I apply the manifest, puppet tries to install the packages (percona-server-server-5.6) but apt can't find those (because the source is not added to sources.list)

so, I added it manually, but then, mysql refuses to load because `/etc/mysql/conf.d` is missing.

I guess I'm missing something but I'm not sure why. Please ask if you need anything else to debug this.

Thanks!

**Comment by gregschoen** [comment]
You have to pass the `manage_repo` flag to the percona class, by default it is false:

``` puppet
class { 'percona':
  server => true,
  percona_version => '5.6',
  manage_repo => true,
}
```

It took me a little while before I saw the `if $::percona::manage_repo` in the preinstall class.

After adding `manage_repo => true` the sources file was created properly:

```
# ls -la /etc/apt/sources.list.d/
-rw-r--r-- 1 root root  104 Mar 21 14:31 percona.list
```

**Comment by arioch** [comment]
Closing this one since it's been answered by @gregschoen.
