### ISSUE TITLE
Git Submodule Pulling Nothing

### ISSUE THREAD

**Issue by JREAM** [arioch/puppet-percona#33]
We have the following:

```
[submodule "puppet/modules/percona"]
    path = puppet/modules/percona
url = https://github.com/arioch/puppet-percona.git
branch = master
```

This is not pulling anything and we don't know why. We can download the zip and place the files in the proper place to get it functioning from the exact URL provided above.

**Comment by arioch** [comment]
I ran a quick test...
Could you repeat these steps and report back?

```
percona ☃  git init
Initialized empty Git repository in /tmp/percona/.git/

percona(master #) ☃  git submodule add https://github.com/arioch/puppet-percona.git modules/percona
Cloning into 'modules/percona'...
remote: Reusing existing pack: 1246, done.
remote: Total 1246 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (1246/1246), 225.21 KiB | 169.00 KiB/s, done.
Resolving deltas: 100% (548/548), done.
Checking connectivity... done.

percona(master #) ☃  ls modules/percona/
Gemfile    Guardfile  LICENSE    Modulefile README.md  Rakefile   lib        manifests  spec       templates

percona(master #) ☃  cat .gitmodules
[submodule "modules/percona"]
  path = modules/percona
  url = https://github.com/arioch/puppet-percona.git
```

The only difference I notice is the modules path and the lack of branch in my config.
Could have been a hickup at github?

**Comment by JREAM** [comment]
I'm not sure, It's happened 2 days now on 3 people's computers :(

On Wed, Jun 11, 2014 at 4:16 AM, Tom De Vylder notifications@github.com
wrote:

> I ran a quick test...
> Could you repeat these steps and report back?
> 
> percona ☃  git init
> Initialized empty Git repository in /tmp/percona/.git/
> 
> percona(master #) ☃  git submodule add https://github.com/arioch/puppet-percona.git modules/percona
> Cloning into 'modules/percona'...
> remote: Reusing existing pack: 1246, done.
> remote: Total 1246 (delta 0), reused 0 (delta 0)
> Receiving objects: 100% (1246/1246), 225.21 KiB | 169.00 KiB/s, done.
> Resolving deltas: 100% (548/548), done.
> Checking connectivity... done.
> 
> percona(master #) ☃  ls modules/percona/
> Gemfile    Guardfile  LICENSE    Modulefile README.md  Rakefile   lib        manifests  spec       templates
> 
> percona(master #) ☃  cat .gitmodules
> [submodule "modules/percona"]
>   path = modules/percona
>   url = https://github.com/arioch/puppet-percona.git
> 
> The only difference I notice is the modules path and the lack of branch in
> my config.
> Could have been a hickup at github?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arioch/puppet-percona/issues/33#issuecomment-45713959
> .

## 

*JREAM http://jream.comYouTube http://youtube.com/jreamdesign *

**Comment by vStone** [comment]
Could you please provide equal output as @arioch has provided, perhaps with some verboseness added? We don't have a lot to go on here.

**Comment by JREAM** [comment]
Submodule path 'www': checked out '1af170e1e068e432263a87a1db39c1193596ca2a'
Unable to checkout 'ca514218d8c34971d21208d402596c56452ca49d' in submodule path 'puppet/modules/percona'

**Comment by vStone** [comment]
Have you tried cleaning out your percona folder and re-initialize it with git submodules? Looks like a local problem.

**Comment by arioch** [comment]
No response for over a month.
I'm guessing the problem was indeed local, hence closing.
