### ISSUE TITLE
Install of 5.5 on Ubuntu/Debian is broken

### ISSUE THREAD

**Issue by erik-smit** [arioch/puppet-percona#5]
manifests/install.php does:

  case $percona_version {
    '5.5': {
      package { $pkg_compat:
        ensure => 'present',
        before => Package[$pkg_common];
      }
    }
    default: {
    }
  }

But $pkg_compat is not set (or existing) on debian|ubuntu, causing install to fail with:

err: /Stage[main]/Percona::Install/Package[undef]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install undef' returned 100: Reading package lists...

**Comment by arioch** [comment]
Should work now with your patch.
Thanks!
