### ISSUE TITLE
Slave missing files

### ISSUE THREAD

**Issue by guzmanbraso** [arioch/puppet-percona#6]
Hi!

Slave setup is broken and require user to add directory & files to module.

Can you provide please the default files?

I've found a workaround by setting up server with puppet-percona but leave importing data and slave setup to an outside class. 

Thanks!

Guzman

**Comment by arioch** [comment]
This was fixed in [0b9d8e9] Add missing templates.
Didn't notice there was a ticket for it as well. Anyhow should be fixed.
